### ISSUE TITLE
'Key error' on pretrained models when doing AMR parsing

### ISSUE THREAD

**Issue by ntu-zjy** [zhangzx-uiuc/AMR-IE#9]
I tried the code and pretrained model that you share, and met problems below.
`2022-11-25 11:37:25 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "testAMR.py", line 3, in <module>
    parser = AMRParser.from_checkpoint(in_checkpoint)
  File "/home/chenjingyuan/nlp/EE/TSAR-main/transition-amr-parser/transition_amr_parser/stack_transformer_amr_parser.py", line 242, in from_checkpoint
    model = load_models(args, task, use_cuda)
  File "/home/chenjingyuan/nlp/EE/TSAR-main/transition-amr-parser/transition_amr_parser/stack_transformer_amr_parser.py", line 32, in load_models
    task=task,
  File "/home/chenjingyuan/anaconda3/envs/transitionamr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 374, in load_model_ensemble
    state,
  File "/home/chenjingyuan/anaconda3/envs/transitionamr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/chenjingyuan/anaconda3/envs/transitionamr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 343, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/chenjingyuan/anaconda3/envs/transitionamr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 681, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/home/chenjingyuan/anaconda3/envs/transitionamr/lib/python3.7/site-packages/fairseq/dataclass/utils.py", line 426, in convert_namespace_to_omegaconf
    _set_legacy_defaults(cfg.model, ARCH_MODEL_REGISTRY[args.arch])
KeyError: 'stack_transformer_6x6_nopos'
`

**Comment by whu-zjy** [comment]
I tried the code and pretrained model that you share, and met problems above.

**Comment by Jarvis658** [comment]
@whu-zjy I also had the same problem, did you solve it?

**Comment by ntu-zjy** [comment]
no, i do not know.



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 25, 2023 18:34 PM
To: ***@***.***&gt;;
Cc: "Jingyuan ***@***.******@***.***&gt;;
Subject: Re: [zhangzx-uiuc/AMR-IE] 'Key error' on pretrained models when doingAMR parsing (Issue #9)




 
@whu-zjy I also had the same problem, did you solve it?
